version: "2"         # required to adjust maintainability checks

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  identical-code:
    enabled: true
    #config:
    #  threshold: #language-specific defaults. overrides affect all languages.
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
    #config:
    #  threshold: #language-specific defaults. overrides affect all languages.

plugins:
  bandit:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - TODO
        - FIXME
        - HACK
        - BUG
        - XXX
  radon:
    enabled: true
    config:
      python_version: 3
      threshold: "A"
  sonar-python:
    enabled: true
    config:
      test_patterns:
        - tests/**
      minimum_severity: major # info, minor, major (default), critical, blocker

exclude_patterns:
  - ".github/"
  - "docs/"
